### ISSUE TITLE
selectedModel not defined in configuration

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#10]
Hi, there is another [issue](https://github.com/thomaskuestner/CNNArt/blob/ab086c37d9b290b143d5be52adaa7de699dab87d/main.py#L69) when running the `main.py`.

```
    lDatasets = cfg[cfg['selectedModel']]['dataref'] + cfg['selectedDatabase']['dataart']
    iLabels = cfg[cfg['selectedModel']]['dataref'] + cfg['selectedDatabase']['labelart']
```
These two lines specify the `selectedModel` in param.yml which is not defined in it. I'm quite confused by it - should it be `selectedDatabase` instead or should it be defined in `param.yml` ourselves?

There are still some other bugs after I change it to `selectedDatabase` - not sure if the program works under your environment.

**Comment by thomaskuestner** [comment]
I recentely changed some parameters and introduced the config file. This should now work: https://github.com/thomaskuestner/CNNArt/commit/ab086c37d9b290b143d5be52adaa7de699dab87d
