### ISSUE TITLE
error in motion_VNetArt.py

### ISSUE THREAD

**Issue by annikaliebgott** [thomaskuestner/CNNArt#102]
Problem with VNetArt (while training on NAKO-IQA data, python 3.6):

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis.

Keras seems to do something weird in terms of dimension ordering. A quick fix is to insert the following code after line 16:

from keras import backend as K
K.set_image_dim_ordering('th')

That solves the problem. Don't know if that's an issue for other data as well, so it would be good to check that for other databases.

**Comment by thomaskuestner** [comment]
thanks. Yes this network is channel first ordering.
This has been fixed.
