### ISSUE TITLE
some bugs in main.py

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#11]
Hi all, I still have some problems when running the `main.py` program in master.  I've made a summary here:

1. [`lDatasets`](https://github.com/thomaskuestner/CNNArt/blob/master/main.py#L69) should be not be defined as 
```
lDatasets = cfg['selectedDatabase']['dataref'] + cfg['selectedDatabase']['dataart']
```
 otherwise it would be a concatenated string instead of a list (the same to `iLabels` below it)

2. In [line 74](https://github.com/thomaskuestner/CNNArt/blob/master/main.py#L74) where `tmpPatches` and `tmpLabels` are defined: 
```
tmpPatches, tmpLabels  = datapre.fPreprocessData(os.path.join(dbinfo.sPathIn, os.sep, pat, os.sep, dbinfo.sSubDirs[1], os.sep, seq), cfg['patchSize'], cfg['patchOverlap'], 1 )
```
I think `os.sep` should not be added here, otherwise it will pass `seq` as `pathDicom` to DataProcessing.py

3. In DataProcessing.py [in line 99](https://github.com/thomaskuestner/CNNArt/blob/master/utils/DataPreprocessing.py#L99), `loadMark` is specified as 
```
loadMark = shelve.open("C:/Users/Sebastian Milde/Pictures/Universitaet/Masterarbeit/Markings/" + proband + ".slv")
```
 where is address is not a valid one.

Could you please look into these issues? Thank you so much.

**Comment by thomaskuestner** [comment]
you need to change the config definition of dataref and dataart
solved: https://github.com/thomaskuestner/CNNArt/commit/f6f145fe6e4c9c5e813f491a332f1607ec85184d

**Comment by TokenJan** [comment]
@thomaskuestner Hi Thomas, it seems we should add `[]` (list) instead if `{}` (dictionary)
and could you also please look into the other two issues I mentioned above?

**Comment by thomaskuestner** [comment]
for the last point you have to talk to @SebastianMilde
