### ISSUE TITLE
data splitting problem

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#13]
When performing training and testing data splitting, only `normal` mode is working while `crossvalidation_data` and `crossvalidation_patient` functions still have some bugs. The problem is `X_train`, `y_train`, `X_test` and `y_tset` should be returned as a list instead of dictionary to be written into h5 file via `hf.create_dataset`.

**Comment by TokenJan** [comment]
should be fixed: [c4c09](https://github.com/thomaskuestner/CNNArt/commit/c4c09cb22d1075afa50046a08e695d5b6fe65722) and [56d4c](https://github.com/thomaskuestner/CNNArt/commit/56d4c8ba1e7735d965ad747359e68b315d7136db)

**Comment by thomaskuestner** [comment]
closed
