### ISSUE TITLE
parameter problems in motion_all_CNN2D.py

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#14]
Following piece of code fragment defines the function `fTrain` in motion_all_CNN2D.py, however the parameters `batchSizes` imported from param.yaml is defined is [128](https://github.com/thomaskuestner/CNNArt/blob/master/config/param.yml#L60) which is not iterable here. `learningRates` is defined as [`[0.1, 0.01, 0.05, 0.005, 0.001]`](https://github.com/thomaskuestner/CNNArt/blob/master/config/param.yml#L61) in param.yaml. Shall we define `batchSizes` and `learningRates` as a list here to make them iterable as well? And since @MarvinJandt has uploaded new files for CNN model - is this motion_all_CNN2D.py deprecated and do we need to switch to 2D_CNN.py instead?
```
def fTrain(X_train, y_train, X_test, y_test, sOutPath, patchSize, batchSizes=None, learningRates=None, iEpochs=None):
    # grid search on batch_sizes and learning rates
    # parse inputs
    batchSizes = 64 if batchSizes is None else batchSizes
    learningRates = 0.01 if learningRates is None else learningRates
    iEpochs = 300 if iEpochs is None else iEpochs
    for iBatch in batchSizes:
        for iLearn in learningRates:
            fTrainInner(X_train, y_train, X_test, y_test, sOutPath, patchSize, iBatch, iLearn, iEpochs)
```

**Comment by TokenJan** [comment]
should be fix here: [0ab5b](https://github.com/thomaskuestner/CNNArt/commit/0ab5b19f6e02a37032dfe079aad201ba0e5d4582)

**Comment by thomaskuestner** [comment]
closed
