### ISSUE TITLE
function parameters mismatch in 2D_CNN.py

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#15]
Hi Marvin, recently you have uploaded the file 2D_CNN.py. But  the function parameters mismatch compared with the call in cnn_main.py. 
For example the cnn model is called in cnn_main.py as follows:
```
cnnModel.fTrain(dData['X_train'], dData['y_train'], dData['X_test'], dData['y_test'], sOutPath, dData['patchSize'], iBatchSize, iLearningRate, iEpochs)
```
but the `fTrain` function is defined in 2D_CNN.py as follows:
```
def fTrain(sOutPath, patchSize,sInPaths=None,sInPaths_valid=None,X_train=None, Y_train=None, X_test=None, Y_test=None, CV_Patient=0, model='motion_head'):#rigid for loops for simplicity
    #add for loops here
    learning_rate = 0.001
    cnn= fCreateModel(patchSize, learningRate=learning_rate, optimizer='Adam')
    print "Model: 2D_CNN"
    fTrainInner(cnn, X_train, Y_train, X_test, Y_test, sOutPath, CV_Patient=CV_Patient,
         batchSize=64, iEpochs=300)
```
I'm not sure if there are other mismatches in the other functions and/or files, could you please take a look? @MarvinJandt

**Comment by TokenJan** [comment]
should be fixed here: [64d1c](https://github.com/thomaskuestner/CNNArt/commit/64d1c546adb070a66330b54ab206fce48466da52)

**Comment by thomaskuestner** [comment]
closed
