### ISSUE TITLE
Add labeling to patching

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/CNNArt#27]
combine both patching methods into the same function call to "fRigidPatching" with the only difference (if-condition) for a patch-wise or volume-wise label. So in both cases dLables is returned but for the volume-wise case it is not used in the calling function.

In the config, I would set a new parameter "sLabeling" with "volume" or "patch" (which is handed over)
Leave the parameter sPatching as it is

**Comment by TokenJan** [comment]
should be fixed by #30

**Comment by thomaskuestner** [comment]
closed
