### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/CNNArt#43]
Implement dynamic data loading (DICOM) + patching + scaling to be processed in mini-batch training
Have a look at the current loading, patching and scaling functions and modify them accordingly.

**Comment by thomaskuestner** [comment]
Following this idea from our segmentation toolbox, we can also set it up here:
[MemoryManagement.pdf](https://github.com/thomaskuestner/CNNArt/files/1660004/MemoryManagement.pdf)
@ywlhlm Can you take responsibility for that?

**Comment by ywlhlm** [comment]
Yes

**Comment by thomaskuestner** [comment]
solved with TFrecords integration
