### ISSUE TITLE
merge the codes from utilsTkinter into utils

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#61]
Since @SebastianMilde made some optimization on the previous codes from utils e.g. Patching and Unpatching, can we merge it into the utils code so that all of us can share?

**Comment by thomaskuestner** [comment]
I will have a look into it...

**Comment by thomaskuestner** [comment]
The code in `utils` is more evolved than in `utils/utilsTKinter`. The only major differences reside in:
- `utils/utilsTKinter/Training_Test_Split.py`: more data is being stored
- `utils/utilsTKinter/Unpatching.py`: 2D/3D unpatching is available

Can we only move the unpatching code?
For backward compatibility I would keep `fRigidUnpatching` function...

See https://github.com/thomaskuestner/CNNArt/commit/ebc9c7c31d87a4e7ba13845559044ed8b169c580 if this works

**Comment by thomaskuestner** [comment]
Ok I agree that this are necessary improvements.

@SebastianMilde Can you recall your changes? 
From comparing the codes, the only improvements I can tell are:
- `math.ceil` is omitted
- dPatches and dLabels are preallocated and correclty assigned, instead of copy over (e.g. line 60 in `utils/Patching.py`)

@TokenJan Could you include these modifcations in `utils/Patching.py` and test it please?

**Comment by TokenJan** [comment]
ok, I will record the time if possible

**Comment by TokenJan** [comment]
I have just tested on my local pc:

- patch size: [80, 80]
- lScaleFactor : [0.5, 1, 2]

the current `fRigidPatching` takes: 2875.377014 seconds
the new `fRigidPatching` takes: 87.181631 seconds

The preallocated `dPatches` really make a huge improvement - and the patching results are the same. I think we can just replace the previous one.

**Comment by thomaskuestner** [comment]
Alright, keeping fingers cross that the remainder of the code such as multi-scaling and dynamic loading is still working.
@ywlhlm @Sakaaaa If you encounter any problems with these modifications, let me know.

**Comment by thomaskuestner** [comment]
Solved with #62
