### ISSUE TITLE
wrong number of patches in Patching

### ISSUE THREAD

**Issue by TokenJan** [thomaskuestner/CNNArt#67]
The number of patches is not calculated correctly [here](https://github.com/thomaskuestner/CNNArt/blob/master/utils/Patching.py#L37) when `patchSize` is [48, 48], `patchOverlap` is 0.8. (Head dataset)

In this case, `idxPatch` is 14080 while `nbPatches ` is 15277, which would include additional black patches.

Also in 3D patching case: `patchSize` is [48, 48, 4], `patchOverlap` is 0.8. (Head dataset)
`idxPatch` is 13024 while `nbPatches ` is 14208.

It does calculate correctly in some cases like [80, 80] with overlap 0.8 and [80, 80, 10] with overlap 0.8. I assume this formula is not able to deal with the cases when it is not divisible.

**Comment by thomaskuestner** [comment]
If the number is not dividable, we zero-pad it to the correct size.
So the implementation is doing the right thing!
You have to be careful which parameters you choose. We can maybe add a warning message that zero-padding is applied and to which extend.

**Comment by TokenJan** [comment]
I didn't think I explain it clearly before. I know we have zero padding in the implementation. But the point is for example in the case of `patchSize`: [48, 48] and `patchOverlap`: 0.8. We initialize a 3D zero numpy array with size (48, 48, 15277), but only allocate 14080 patches in it, which makes the rest  1197 patches meaningless (all 0) for training. What I mean is it is inconsistent between the actual patch number (14080) and the pre-initialized patch number (15277) - I think they still should be kept the same after zero-padding.

**Comment by thomaskuestner** [comment]
Thanks for clarification.
This looks like `nbPatches` is calculated wrong.
A quick workaround could be adding:
in 2D:
`dPatches = dPatches[:,:,0:idxPatch-1]`
and in 3D:
`dPatches = dPatches[:,:,:,0:idxPatch-1]`
as well as for `dLabels`

**Comment by TokenJan** [comment]
should be fixed now #68 
maybe we should look into the correct `nbPatches` in the future

**Comment by TokenJan** [comment]
@thomaskuestner Hi Thomas, I think `dPatches` should be `dPatches[:,:,0:idxPatch]` instead of `dPatches[:,:,0:idxPatch-1]`. 

For example: The last allocated patch is with `idxPatch`: 14079, then `idxPatch` equals 14080 after `idxPatch += 1`. Then it should be fine just crop `dPatches` to `dPatches[:,:,0:idxPatch]` without includuing `dPatches[:,:,14080]`

**Comment by thomaskuestner** [comment]
Thanks, corrected https://github.com/thomaskuestner/CNNArt/commit/6e44553e73706ed22d598131ed6b091178e03ac9
I had the wrong programming language in my head ^^
