### ISSUE TITLE
GUI clean up and merge to master

### ISSUE THREAD

**Issue by thomaskuestner** [thomaskuestner/CNNArt#77]
- Merge branch PyQt_GUI_ziWEI to master

- remove duplicated files and link to original ones:
`GUI/PyQt/DatabaseInfo.py`
`GUI/PyQt/MRData.py`
`GUI/PyQt/config`

- rename:
`GUI/PyQt/Unpatch_eleven.py` -> `GUI/PyQt/Unpatch.py`

- add README how to call GUI

**Comment by ZiweiWU713** [comment]
should be fixed in #84
