### ISSUE TITLE
SyntaxError: non-keyword arg after keyword arg

### ISSUE THREAD

**Issue by wzehui** [thomaskuestner/CNNArt#95]
CNNArt/main.py", line 141
tmpPatches, tmpLabels  = datapre.fPreprocessData(os.path.join(dbinfo.sPathIn, pat, dbinfo.sSubDirs[1], seq), scpatchSize, cfg['patchOverlap'], 1, cfg['sLabeling'], sTrainingMethod=sTrainingMethod, cfg['range'])

**Comment by thomaskuestner** [comment]
solved
