### ISSUE TITLE
missed input 'range_norm'

### ISSUE THREAD

**Issue by wzehui** [thomaskuestner/CNNArt#99]
File "/CNNArt/main.py", line 128, in <module>
 tmpPatches, tmpLabels  = datapre.fPreprocessData(os.path.join(dbinfo.sPathIn, pat, dbinfo.sSubDirs[1], seq), scpatchSize, cfg['patchOverlap'], 1, cfg['sLabeling'], sTrainingMethod=sTrainingMethod)

**Comment by thomaskuestner** [comment]
solved
